### ISSUE TITLE
Specifying continuous constraints

### ISSUE THREAD

**Issue by richy1996** [tsitsimis/constrainedlr#1]
Is there a way to be more granular with the constraints? i.e. specify 0.5 instead of 1 e.g.? thanks

**Comment by tsitsimis** [comment]
Hi! The constraints are for the **signs** of the coefficients only. They don't specify the values of the coefficients. This means that a constraint of 1 means positive coefficient, and -1 means negative.

Since you asked, do you have a use case where constraints on the **values** of the coefficients would be needed?

**Comment by richy1996** [comment]
Yes I'm trying to find a package that has the algorithm in this paper ([Combining Alphas via Bounded Regression](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2550335)) already implemented basically. Basically it's constrained and also weighted regression. I see that your algorithm can handle weighted but can only handle sign constraints as you mentioned. The algorithm in [constrained-linear-regression](https://pypi.org/project/constrained-linear-regression/) can handle constraints on the values but doesn't accept weights as I understand it.
There's R code in the paper but I'd prefer to not dig into that in detail until i have to.

**Comment by tsitsimis** [comment]
I think it totally makes sense! I was planning of something similar as well. I will work on it as soon as I find some time

**Comment by tsitsimis** [comment]
Hey @richy1996. In the new version, value constraints are added!
You can now specify a lower and/or an upper bound of one or more coefficients. Check the example in the package [documentation](https://tsitsimis.github.io/constrainedlr/).

Let me know of any comments or additional features that would be helpful

**Comment by richy1996** [comment]
Sweet! I'll have a look and refer back
